# Generated by Django 3.2 on 2024-12-01 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0002_libro_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Debe ser un correo válido.')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener entre 8 y 15 dígitos, con o sin prefijo '+' al inicio.", regex='^\\+?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Correo incorrecto.')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefono incorrecto. Ejemplo: +56912345678', regex='^(?:\\+56|56)?9\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, message='La contraseña debe tener al menos 8 caracteres.'), django.core.validators.RegexValidator(message='La contraseña debe incluir al menos una letra, un número y un símbolo especial.', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato chileno: 12.345.678-9 o 1.234.567-K.', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9kK]$')]),
        ),
    ]
