# Generated by Django 3.2 on 2024-12-02 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0003_auto_20241130_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(help_text='Escribe tu comentario aquí.', max_length=500, validators=[django.core.validators.MinLengthValidator(1, message='El comentario no puede estar vacío.')])),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el comentario.', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppBiblioteca.usuario')),
            ],
        ),
    ]
