# Generated by Django 3.2 on 2024-12-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0004_auto_20241202_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
